parameters:
  environment: "dev"
  azureServiceConnection: "ARM_SUBSCRIPTION"

  terraformValidate: false
  terraformPlan: true
  terraformApply: false
  terraformDestroy: true
jobs:
  - job: terraform_deploy
    displayName: "Terraform deploy"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - template: ../variables/terraform-variables.yml
        parameters:
          environment: $(environment)
    steps:
      - template: ../steps/terraform-delivery-steps.yml
        parameters:
          environment: ${{ parameters.environment }}
          azureServiceConnection: ${{ parameters.azureServiceConnection }}
          terraformValidate: ${{ parameters.terraformValidate }}
          terraformPlan: ${{ parameters.terraformPlan }}
          terraformApply: ${{ parameters.terraformApply }}
          terraformDestroy: ${{ parameters.terraformDestroy }}
