parameters:
  environment: "dev"
  azureServiceConnection: "ARM_SUBSCRIPTION"

  terraformFormat: true
  terraformValidate: false
  terraformPlan: false
  terraformApply: false
  terraformDestroy: false
jobs:
  - job: terraform_format
    displayName: "Terraform format"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - template: ../variables/terraform-variables.yml
        parameters:
          environment: $(environment)
    steps:
      - template: ../steps/terraform-delivery-steps.yml
        parameters:
          environment: ${{ parameters.environment }}
          azureServiceConnection: ${{ parameters.azureServiceConnection }}
          terraformFormat: ${{ parameters.terraformFormat }}
          terraformValidate: ${{ parameters.terraformValidate }}
          terraformPlan: ${{ parameters.terraformPlan }}
          terraformApply: ${{ parameters.terraformApply }}
          terraformDestroy: ${{ parameters.terraformDestroy }}
