parameters:
  environment: "dev"

trigger:
  - "app"
  - "app/*"
  - "main"

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "acrpmorosactivity5dev001"
              repository: "voting-app"
              command: "build"
              Dockerfile: "**/app/Dockerfile"
              tags: "latest"
          - task: Docker@2
            inputs:
              containerRegistry: "acrpmorosactivity5dev001"
              repository: "voting-app"
              command: "push"
              tags: "latest"
  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: ${{ parameters.environment }}
        strategy:
          canary:
            trafficRouting:
              type: "weighted"
              weight: 20
            preApproval:
              conditions:
                - environment: ${{ parameters.environment }}
                  result: "succeeded()"
        pool:
          vmImage: "ubuntu-latest"
        variables:
          - group: ACR_credentials
          - group: AKS_credentials
        steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: Deploy to AKS
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "kubepmorosactivity5dev001"
              namespace: "default"
              command: "create"
              arguments: "-f $(System.DefaultWorkingDirectory)/app/k8s-deploy-aks.yaml"
