trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - "infrastructure"
      - "infrastructure/*"
      - "infrastructure/*/*"
      - "ci-terraform-pipeline.yml"
      - "cd-terraform-pipeline.yml"
    exclude:
      - "README.md"
pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: TerraformDeploy
    displayName: "Terraform deploy"
    jobs:
      - template: pipelines-templates/jobs/terraform-deploy.yml
        parameters:
          environment: "dev"
          azureServiceConnection: "ARM_SUBSCRIPTION"
